version: "3"

tasks:
  apply:
    env:
      ENCRYPTED: false
    cmds:
      - touch ~/.config/chezmoi/chezmoistate.boltdb # Prevent creating chezmoistate with sudo
      - sudo -E chezmoi apply --source ./root --destination /
      - chezmoi apply --source ./home --destination "$HOME" # Scripts should be run after /root directory is applied

      # - chezmoi state delete-bucket --bucket=entryState
      # - chezmoi state delete-bucket --bucket=scriptState

  merge:
    env:
      SOPS_AGE_KEY:
        sh: secret-tool lookup sops-age-project dotfiles
    cmds:
      # Regarding root merge-all, we are doing 2 way merge, so it does not update the target file, for that we have to issue "task apply"
      - sudo -E chezmoi merge-all --source ./root --destination /
      - chezmoi merge-all --source "./home"

  git-setup:
    cmds:
      - pre-commit autoupdate
      - pre-commit install
