#!/bin/bash

# Enable safe execution flags
set -euo pipefail

# Chaotic-AUR: https://aur.chaotic.cx/
if ! which chaotic-mirrorlist &>/dev/null; then
    echo "Configuring Chaotic-AUR"
    sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
    sudo pacman-key --lsign-key 3056513887B78AEB
    sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
    sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
fi

# Check if the locale is already generated by looking for locale files
if ! locale -a | grep -q 'en_US.utf8'; then
    echo "Locale not generated. Generating locales now..."
    sudo locale-gen
    locale
fi
