#!/bin/bash

# Enable safe execution flags
set -euo pipefail

# Check if the locale is already generated by looking for locale files
if ! locale -a | grep -q 'en_US.utf8'; then
    echo "Locale not generated. Generating locales now..."
    sudo locale-gen
    locale
fi
