#!/bin/bash

# Enable safe execution flags
set -euo pipefail


# curl -fsSL https://get.jetify.com/devbox | bash
# sh <(curl -L https://nixos.org/nix/install) --daemon

# Nix package manager
sudo systemctl enable --now nix-daemon.service

sudo groupadd -f nix-users
sudo usermod -aG nix-users $USER

# Check if the locale is already generated by looking for locale files
if ! locale -a | grep -q 'en_US.utf8'; then
    echo "Locale not generated. Generating locales now..."
    sudo locale-gen
    locale
fi
